[package]
name = "hc_zome_rea_agreement"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.1.1"

hc_zome_rea_agreement_rpc = { path = "../rpc" }
hc_zome_rea_agreement_lib = { path = "../lib" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
