[package]
name = "hc_zome_rea_recipe_flow"
version = "0.1.0"
authors = ["leo <leoproechel@gmail.com>"]
edition = "2023"

[dependencies]
serde = { workspace = true }
hdk = { workspace = true }

hc_zome_rea_recipe_flow_rpc = { path = "../rpc" }
hc_zome_rea_recipe_flow_lib = { path = "../lib" }
hc_zome_rea_recipe_flow_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
