language: nix
script: nix-shell --run 'npm run dht:sim2h & yarn && npm run build && npm run test:integration:test'
git:
  quiet: true
  depth: false
  submodules: true
branches:
  only:
  - master
  - /^(feature|release|hotfix)\/.*/
