[package]
name = "hc_zome_rea_economic_event_index_observation"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = { workspace = true }
hdk = { workspace = true }

hdk_semantic_indexes_zome_lib = { path = "../../../lib/hdk_semantic_indexes/zome" }
hdk_semantic_indexes_core = { path = "../../../lib/hdk_semantic_indexes/integrity_core" }
hdk_semantic_indexes_zome_derive = { path = "../../../lib/hdk_semantic_indexes/zome_derive" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_economic_event_rpc = { path = "../rpc" }
hc_zome_rea_economic_event_storage_consts = { path = "../storage_consts" }
hc_zome_rea_economic_resource_storage_consts = { path = "../../rea_economic_resource/storage_consts" }
hc_zome_rea_process_storage_consts = { path = "../../rea_process/storage_consts" }
hc_zome_rea_commitment_storage_consts = { path = "../../rea_commitment/storage_consts" }
hc_zome_rea_satisfaction_storage_consts = { path = "../../rea_satisfaction/storage_consts" }
hc_zome_rea_agreement_storage_consts = { path = "../../rea_agreement/storage_consts" }
hc_zome_rea_fulfillment_storage_consts = { path = "../../rea_fulfillment/storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
