[package]
name = "hc_zome_rea_unit_storage"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "*"
hdk = "*"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
hc_zome_rea_unit_rpc = { path = "../rpc" }
hc_zome_dna_auth_resolver_core = {git = "https://github.com/holochain-open-dev/dna-auth-resolver", tag = "0.2.0", package = "hc_zome_dna_auth_resolver_lib"}

[lib]
crate-type = ["lib"]
