[package]
name = "hc_zome_rea_proposed_intent_rpc"
version = "0.1.0"
authors = ["Jhonatan Hern <jhonatanhernandez998@gmail.com>"]
edition = "2018"

[dependencies]
serde = { workspace = true }
holochain_serialized_bytes = { workspace = true }

vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }

[lib]
crate-type = ["lib"]
