[package]
name = "hc_zome_rea_recipe_process_index_recipe"
version = "0.1.0"
authors = ["leo <leoproechel@gmail.com>"]
edition = "2018"

[dependencies]
serde = { workspace = true }
hdk = { workspace = true }

hdk_semantic_indexes_zome_lib = { path = "../../../lib/hdk_semantic_indexes/zome" }
hdk_semantic_indexes_core = { path = "../../../lib/hdk_semantic_indexes/integrity_core" }
hdk_semantic_indexes_zome_derive = { path = "../../../lib/hdk_semantic_indexes/zome_derive" }
hc_zome_rea_recipe_process_rpc = { path = "../rpc" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
