[package]
name = "hc_zome_rea_process_specification"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = { workspace = true }
hdk = { workspace = true }

hc_zome_rea_process_specification_rpc = { path = "../rpc" }
hc_zome_rea_process_specification_lib = { path = "../lib" }
hc_zome_rea_process_specification_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
