[package]
name = "hc_zome_rea_proposed_to"
version = "0.1.0"
authors = ["JhonatanHern <jhonatanhernandez998@gmail.com>", "pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "1"
# :DUPE: hdk-rust-revid
hdk = "0.1.1"

hc_zome_rea_proposed_to_rpc = { path = "../rpc" }
hc_zome_rea_proposed_to_lib = { path = "../lib" }
hc_zome_rea_proposed_to_storage_consts = { path = "../storage_consts" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib"]
