[package]
name = "hc_zome_rea_fulfillment_rpc"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "*"
serde_bytes = "*"
holochain_serialized_bytes = "*"

serde_maybe_undefined = { path = "../../../lib/serde_maybe_undefined" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }
vf_measurement = { path = "../../../lib/vf_measurement" }

[lib]
crate-type = ["lib"]
