[package]
name = "hc_zome_rea_recipe_process_integrity"
version = "0.1.0"
authors = ["leo <leoproechel@gmail.com>"]
edition = "2023"

[dependencies]
serde = { workspace = true }
hdi = { workspace = true }

hc_zome_rea_recipe_process_storage = { path = "../storage" }

[lib]
path = "src/lib.rs"
crate-type = ["cdylib", "rlib"]
