/**
 * Observation module datatypes & behaviours
 */

extern crate serde;
#[macro_use]
extern crate serde_derive;
extern crate serde_json;

extern crate vf_core;

pub use vf_core::{ type_aliases, measurement };

pub mod process_specification;
pub mod resource_specification;
pub mod unit;

pub mod identifiers {
    pub const ECONOMIC_RESOURCE_SPECIFICATION_ENTRY_TYPE: &str = "ECONOMIC_RESOURCE_SPECIFICATION_ENTRY_TYPE";
    pub const ECONOMIC_RESOURCE_SPECIFICATION_BASE_ENTRY_TYPE: &str = "ECONOMIC_RESOURCE_SPECIFICATION_BASE_ENTRY_TYPE";
    pub const ECONOMIC_RESOURCE_SPECIFICATION_INITIAL_ENTRY_LINK_TYPE: &str = "ECONOMIC_RESOURCE_SPECIFICATION_INITIAL_ENTRY_LINK_TYPE";
    pub const ECONOMIC_RESOURCE_SPECIFICATION_CONFORMING: &str = "ECONOMIC_RESOURCE_SPECIFICATION_CONFORMING";
    pub const ECONOMIC_RESOURCE_SPECIFICATION_CONFORMING_TAG: &str = "ECONOMIC_RESOURCE_SPECIFICATION_CONFORMING_TAG";

    pub const PROCESS_SPECIFICATION_ENTRY_TYPE: &str = "PROCESS_SPECIFICATION_ENTRY_TYPE";
    pub const PROCESS_SPECIFICATION_BASE_ENTRY_TYPE: &str = "PROCESS_SPECIFICATION_BASE_ENTRY_TYPE";
    pub const PROCESS_SPECIFICATION_INITIAL_ENTRY_LINK_TYPE: &str = "PROCESS_SPECIFICATION_INITIAL_ENTRY_LINK_TYPE";

    pub const UNIT_ENTRY_TYPE: &str = "UNIT_ENTRY_TYPE";
    pub const UNIT_ID_ENTRY_TYPE: &str = "UNIT_ID_ENTRY_TYPE";
    pub const UNIT_INITIAL_ENTRY_LINK_TYPE: &str = "UNIT_INITIAL_ENTRY_LINK_TYPE";
    pub const UNIT_INITIAL_ENTRY_LINK_TAG: &str = "UNIT_ENTRY_LINK_TAG";
}
