[package]
name = "hc_zome_rea_unit_rpc"
version = "0.1.0"
authors = ["pospi <pospi@spadgos.com>"]
edition = "2018"

[dependencies]
serde = "*"
holochain_serialized_bytes = "*"

hdk_records = { path = "../../../lib/hdk_records" }
vf_attributes_hdk = { path = "../../../lib/vf_attributes_hdk" }

[lib]
crate-type = ["lib"]
